version: "3.8"

services:
  qls:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qls
    restart: unless-stopped
    ports:
      - "5555:5000"
    volumes:
      - qls-data:/data
    environment:
      PORT: "5000"

volumes:
  qls-data:
